openapi: "3.0.0"
info:
  version: 1.0.0
  title: Generate models
paths:
  /api/auth/register:
    post:
      summary: User registration
      description: Register new user
      operationId: UserRegGen
      requestBody:
        description: User with login, email and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
        '400':
          description: Error creating hash from password
        '409':
          description: Login is used
        '500':
          description: Can't get UUID or user hash 
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/auth/login:
    post:
      summary: User login
      description: Loing user
      operationId: UserLoginGen
      requestBody:
        description: User with login and password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
        '400':
          description: Error creating hash from password
        '409':
          description: Login is used
        '500':
          description: Can't get UUID or user hash 
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      required:
        - login
        - email
        - password
      properties:
        login:
          type: string
          description: User login from registration
        email:
          type: string
          description: User email from registration
        password:
          type: string
          description: User pass from registartion
        jwt:
          type: string
          description: JWT user's token
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    # NOTE that this is not generated by default because it's not referenced. If you want it, you need to use the following YAML configuration:
    #
    # output-options:
    #   skip-prune: true
    Unreferenced:
      type: object
      required:
        - id
      properties:
        id:
          type: int